# Generated by Django 4.1.3 on 2022-11-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_registration_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
